# Generated by Django 4.2 on 2023-08-12 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, unique=True, verbose_name='Title post')),
                ('text', models.TextField(unique=True, verbose_name='Text post')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date post')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Time post')),
                ('views', models.IntegerField(default=1, verbose_name='Number of views')),
                ('likes', models.IntegerField(default=0, verbose_name='Number of likes')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
    ]
