# Generated by Django 4.2 on 2023-08-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('none', 'NONE')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='user_images/default_user.png', upload_to='user_images', verbose_name='User Image'),
        ),
    ]
