# Generated by Django 4.2 on 2023-08-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_profile_options_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='Consent to send email notifications'),
        ),
    ]
